apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-finki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:KristijanBoshev/keda-knative.git
    targetRevision: HEAD
    path: knative
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-knative
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: knative
      namespace: keda-knative
      jsonPointers:
        - /spec/replicas  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-finki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:KristijanBoshev/keda-knative.git
    targetRevision: HEAD
    path: keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-knative
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: keda
      namespace: keda-knative
      jsonPointers:
        - /spec/replicas  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true