apiVersion: v1
kind: Service
metadata:
  name: keda-service
  namespace: keda-knative
  labels:
    app: keda
spec:
  selector:
    app: keda
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
